services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: horizon
    working_dir: /var/www
    volumes:
      - .:/var/www  
    networks:
      - app-network
    ports:
      - "8000:8000"  

  redis:
    image: redis:alpine
    container_name: laravel_redis
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge

